/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as AppExercisesSessionSidRouteImport } from './routes/_app.exercises.session.$sid'
import { Route as AppExercisesSessionSidExerciseEidRouteImport } from './routes/_app.exercises.session.$sid.exercise.$eid'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesSessionSidRoute = AppExercisesSessionSidRouteImport.update({
  id: '/session/$sid',
  path: '/session/$sid',
  getParentRoute: () => AppExercisesRoute,
} as any)
const AppExercisesSessionSidExerciseEidRoute =
  AppExercisesSessionSidExerciseEidRouteImport.update({
    id: '/exercise/$eid',
    path: '/exercise/$eid',
    getParentRoute: () => AppExercisesSessionSidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/exercises': typeof AppExercisesRouteWithChildren
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/support': typeof AppSupportRoute
  '/exercises/session/$sid': typeof AppExercisesSessionSidRouteWithChildren
  '/exercises/session/$sid/exercise/$eid': typeof AppExercisesSessionSidExerciseEidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/exercises': typeof AppExercisesRouteWithChildren
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/support': typeof AppSupportRoute
  '/exercises/session/$sid': typeof AppExercisesSessionSidRouteWithChildren
  '/exercises/session/$sid/exercise/$eid': typeof AppExercisesSessionSidExerciseEidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/_app/exercises': typeof AppExercisesRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/exercises/session/$sid': typeof AppExercisesSessionSidRouteWithChildren
  '/_app/exercises/session/$sid/exercise/$eid': typeof AppExercisesSessionSidExerciseEidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/welcome'
    | '/exercises'
    | '/home'
    | '/profile'
    | '/progress'
    | '/support'
    | '/exercises/session/$sid'
    | '/exercises/session/$sid/exercise/$eid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/welcome'
    | '/exercises'
    | '/home'
    | '/profile'
    | '/progress'
    | '/support'
    | '/exercises/session/$sid'
    | '/exercises/session/$sid/exercise/$eid'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/welcome'
    | '/_app/exercises'
    | '/_app/home'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/support'
    | '/_app/exercises/session/$sid'
    | '/_app/exercises/session/$sid/exercise/$eid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/session/$sid': {
      id: '/_app/exercises/session/$sid'
      path: '/session/$sid'
      fullPath: '/exercises/session/$sid'
      preLoaderRoute: typeof AppExercisesSessionSidRouteImport
      parentRoute: typeof AppExercisesRoute
    }
    '/_app/exercises/session/$sid/exercise/$eid': {
      id: '/_app/exercises/session/$sid/exercise/$eid'
      path: '/exercise/$eid'
      fullPath: '/exercises/session/$sid/exercise/$eid'
      preLoaderRoute: typeof AppExercisesSessionSidExerciseEidRouteImport
      parentRoute: typeof AppExercisesSessionSidRoute
    }
  }
}

interface AppExercisesSessionSidRouteChildren {
  AppExercisesSessionSidExerciseEidRoute: typeof AppExercisesSessionSidExerciseEidRoute
}

const AppExercisesSessionSidRouteChildren: AppExercisesSessionSidRouteChildren =
  {
    AppExercisesSessionSidExerciseEidRoute:
      AppExercisesSessionSidExerciseEidRoute,
  }

const AppExercisesSessionSidRouteWithChildren =
  AppExercisesSessionSidRoute._addFileChildren(
    AppExercisesSessionSidRouteChildren,
  )

interface AppExercisesRouteChildren {
  AppExercisesSessionSidRoute: typeof AppExercisesSessionSidRouteWithChildren
}

const AppExercisesRouteChildren: AppExercisesRouteChildren = {
  AppExercisesSessionSidRoute: AppExercisesSessionSidRouteWithChildren,
}

const AppExercisesRouteWithChildren = AppExercisesRoute._addFileChildren(
  AppExercisesRouteChildren,
)

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppSupportRoute: typeof AppSupportRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppSupportRoute: AppSupportRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
