/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as AppExercisesSessionSidRouteImport } from './routes/_app.exercises.session.$sid'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesSessionSidRoute = AppExercisesSessionSidRouteImport.update({
  id: '/session/$sid',
  path: '/session/$sid',
  getParentRoute: () => AppExercisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/exercises': typeof AppExercisesRouteWithChildren
  '/home': typeof AppHomeRoute
  '/exercises/session/$sid': typeof AppExercisesSessionSidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/exercises': typeof AppExercisesRouteWithChildren
  '/home': typeof AppHomeRoute
  '/exercises/session/$sid': typeof AppExercisesSessionSidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/_app/exercises': typeof AppExercisesRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/exercises/session/$sid': typeof AppExercisesSessionSidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/welcome'
    | '/exercises'
    | '/home'
    | '/exercises/session/$sid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/welcome'
    | '/exercises'
    | '/home'
    | '/exercises/session/$sid'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/welcome'
    | '/_app/exercises'
    | '/_app/home'
    | '/_app/exercises/session/$sid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/session/$sid': {
      id: '/_app/exercises/session/$sid'
      path: '/session/$sid'
      fullPath: '/exercises/session/$sid'
      preLoaderRoute: typeof AppExercisesSessionSidRouteImport
      parentRoute: typeof AppExercisesRoute
    }
  }
}

interface AppExercisesRouteChildren {
  AppExercisesSessionSidRoute: typeof AppExercisesSessionSidRoute
}

const AppExercisesRouteChildren: AppExercisesRouteChildren = {
  AppExercisesSessionSidRoute: AppExercisesSessionSidRoute,
}

const AppExercisesRouteWithChildren = AppExercisesRoute._addFileChildren(
  AppExercisesRouteChildren,
)

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
